### ISSUE TITLE
Ciao

### ISSUE THREAD

**Issue by Percival006** [Lioydiano/Lioydiano.github.io#12]
## Title-of-the-article
[`<Title-of-the-article>`](https://github.com/Lioydiano/Lioydiano.github.io/<article-name>) should be created.

## File
Attach an `.md` or `.txt` file containing the body of the new article.

**Comment by FLAK-ZOSO** [comment]
@Percival006 non hai allegato nessun articolo 🤦‍♀️ah, e sai che questa conversazione è leggibile tipo da tutto il mondo, vero?
Ora cancello questa issue, tu però domani scrivi qualcosa, ricrea una issue come questa, e compila i campi (quelli suggeriti in inglese, compilali pure in italiano).
